#!/bin/sh

NAME="boxset_proxy_app"
FLASKDIR=/webapps/boxset_proxy_app/boxset-proxy-apps
SOCKFILE=/webapps/boxset_proxy_app/run/gunicorn.sock
USER=boxset_app
GROUP=apps
NUM_WORKERS=3

# Set this to 0 for unlimited requests. During development, you might want to
# set this to 1 to automatically restart the process on each request (i.e. your
# code will be reloaded on every request).
MAX_REQUESTS=0

echo "Starting $NAME as `whoami`"
# Activate the virtual environment.
cd $FLASKDIR
echo "CWD is `pwd`"

. ../bin/activate


# Create the run directory if it doesn't exist.
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Programs meant to be run under supervisor should not daemonize themselves
# (do not use --daemon).
exec gunicorn \
    --name $NAME \
    --workers $NUM_WORKERS \
    --max-requests $MAX_REQUESTS \
    --user $USER --group $GROUP \
    --log-level debug \
    --bind unix:$SOCKFILE \
    server:app
